version: '3.8'

# Configuración común de Airflow
x-airflow-common:
  &airflow-common
  build: .
  environment:
    &airflow-common-env
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__WEBSERVER__SECRET_KEY: 'super_secret_key'
    AIRFLOW__LOGGING__LOGGING_LEVEL: INFO
    PYTHONPATH: /opt/airflow
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./src:/opt/airflow/src
    - ./sql:/opt/airflow/sql
    - ./tests:/opt/airflow/tests
  # user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    postgres:
      condition: service_healthy

networks:
  airflow-net:
    driver: bridge

volumes:
  postgres-db-volume:

services:
  # Base de Datos PostgreSQL
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - airflow-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

    # Inicialización de Airflow
  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        # Solo crear directorios (SIN chown)
        mkdir -p /opt/airflow/logs /opt/airflow/dags /opt/airflow/plugins
        
        # Inicializar base de datos
        airflow db init
        
        # Crear usuario admin
        airflow users create \
          --username admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com \
          --password admin
        
        echo "======================================"
        echo "✅ Airflow inicializado!"
        echo "Usuario: admin"
        echo "Contraseña: admin"
        echo "URL: http://localhost:8080"
        echo "======================================"
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
    networks:
      - airflow-net

  # Webserver (UI)
  webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    networks:
      - airflow-net
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  # Scheduler
  scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler
    networks:
      - airflow-net
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully